ClinicalAgenda.Web.MVC/Controllers/ClientsController.cs

using ClinicalAgenda.Data.Repositories;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using ClinicalAgenda.Web.MVC.Models;
using ClinicalAgenda.Domain.Interfaces.Services;
using ClinicalAgenda.Domain.Models;
using ClinicalAgenda.Web.MVC.Extensions;
using ClinicalAgenda.Web.MVC.Controllers;
using ClinicalAgenda.Domain.Interfaces;

namespace ClinicalAgenda.Web.Controllers
{
  public class ClientsController : BaseController<User>
  {

    public ClientsController(IServiceFacade facade) : base(facade)
    {

    }
    // GET: Clients/
    public IActionResult Index()
    {
      var clients = _facade.GetUserService().GetAllClients().Transform<Client, ClientViewModel>();

      return View(clients);
    }

    // GET: Clients/Details/5
    public IActionResult Details(int id)
    {
      var client = _facade.GetUserService().FindClient(id);
      var viewModel = client.Transform<Client, ClientViewModel>();
      LoadSchedulesFor(client);
      if (client is Client)
        return View(viewModel);
      else
      {
        return RedirectToAction("Index");
      }
    }

    // GET: Clients/Edit/5
    public IActionResult Edit(int id)
    {
      var client = _facade.GetUserService().FindClient(id);
      var viewModel = client.Transform<Client, ClientViewModel>();
      if (client is Client)
      {
        return View(viewModel);
      }
      else
      {
        return RedirectToAction("Index");
      }
    }

    // POST: Clients/Edit/5
    [HttpPost]
    public IActionResult Edit(int id, ClientViewModel viewModel)
    {
      var client = viewModel.Transform<ClientViewModel, Client>();
      var result = _facade.GetUserService().Update(client);

      return RespondTo(result, RedirectToAction("Details", new { id = client.Id }), Edit(id));
    }

    private void LoadSchedulesFor(Client client)
    {
      ViewBag.Schedules = _facade.GetScheduleService().SelectByClient(client).Transform<Schedule, ScheduleViewModel>();
    }

  }
}

ClinicalAgenda.Web.MVC/Controllers/JobsController.cs
using ClinicalAgenda.Data.Repositories;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Http;
using ClinicalAgenda.Domain.Interfaces.Repositories;
using ClinicalAgenda.Web.MVC.Models;
using ClinicalAgenda.Domain.Models;
using ClinicalAgenda.Web.MVC.Extensions;
using ClinicalAgenda.Domain.Interfaces.Services;

using ClinicalAgenda.Domain.Interfaces.Validations;
using ClinicalAgenda.Web.MVC.Controllers;
using ClinicalAgenda.Domain.Interfaces;
using System;

namespace ClinicalAgenda.Web.Controllers
{
  public class TreatmentsController : BaseController<Treatment>
  {
    public TreatmentsController(IServiceFacade facade) : base(facade)
    {

    }
    // GET: Schedules
    public IActionResult Index()
    {
      var treatments = _facade.GetTreatmentService().GetAll().Transform<Treatment, TreatmentViewModel>();

      return View(treatments);
    }

    // GET: Schedules/Details/5
    public IActionResult Details(int id)
    {
      var schedule = _facade.GetTreatmentService().Find(id).Transform<Treatment, TreatmentViewModel>();
      return View(schedule);
    }

    // GET: Schedules/Create
    public IActionResult Create()
    {
      LoadTreatmentTypes();
      return View();
    }

    // POST: Schedules/Create
    [HttpPost]
    public IActionResult Create(TreatmentViewModel viewModel)
    {
      var Treatment = viewModel.Transform<TreatmentViewModel, Treatment>();

      var result = _facade.GetTreatmentService().Add(Treatment);
      return RespondTo(result, RedirectToAction("Index"), Create());
    }

    // GET: Schedules/Edit/5
    public IActionResult Edit(int id)
    {
      LoadTreatmentTypes();

      var Treatment = _facade.GetTreatmentService().Find(id).Transform<Treatment, TreatmentViewModel>();
      return View(Treatment);
    }

    // POST: Schedules/Edit/5
    [HttpPost]
    public IActionResult Edit(int id, TreatmentViewModel viewModel)
    {

      var Treatment = viewModel.Transform<TreatmentViewModel, Treatment>();
      var result = _facade.GetTreatmentService().Update(Treatment);

      return RespondTo(result, RedirectToAction("Index"), Edit(id));
    }

    // GET: Schedules/Delete/5
    public IActionResult Delete(int id)
    {
      var schedule = _facade.GetTreatmentService().Find(id).Transform<Treatment, TreatmentViewModel>();
      return View(schedule);

    }

    // POST: /Schdules/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public IActionResult DeleteConfirmed(int id)
    {
      var result = _facade.GetTreatmentService().Remove(id);

      return RespondTo(result, RedirectToAction("Index"), Delete(id));
    }

    private void LoadTreatmentTypes()
    {
      TreatmentType[] treatmentsTypes = (TreatmentType[])Enum.GetValues(typeof(TreatmentType));
      ViewBag.TreatmentTypes = treatmentsTypes.Select(c =>
        new SelectListItem()
        {
          Text = c.ToString(),
          Value = c.ToString()
        });
    }

  }
}

ClinicalAgenda.Web.MVC/Controllers/SchedulesController.cs
using ClinicalAgenda.Data.Repositories;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Http;
using ClinicalAgenda.Domain.Interfaces.Repositories;
using ClinicalAgenda.Web.MVC.Models;
using ClinicalAgenda.Domain.Models;
using ClinicalAgenda.Web.MVC.Extensions;
using ClinicalAgenda.Domain.Interfaces.Services;

using ClinicalAgenda.Domain.Interfaces.Validations;
using ClinicalAgenda.Web.MVC.Controllers;
using ClinicalAgenda.Domain.Interfaces;
using System;

namespace ClinicalAgenda.Web.Controllers
{
  public class SchedulesController : BaseController<Schedule>
  {
    public SchedulesController(IServiceFacade facade) : base(facade)
    {

    }
    // GET: Schedules
    public IActionResult Index()
    {
      var schedules = _facade.GetScheduleService().GetMySchedules(CurrentUser).Transform<Schedule, ScheduleViewModel>();

      return View(schedules);
    }

    // GET: Schedules/Details/5
    public IActionResult Details(int id)
    {
      var schedule = _facade.GetScheduleService().Find(id).Transform<Schedule, ScheduleViewModel>();
      return View(schedule);
    }

    // GET: Schedules/Create
    public IActionResult Create()
    {
      if (CurrentUser is Client)
      {
        BeforeCreateOrEdit();
        return View();
      }
      else
      {
        return RedirectToAction("Index");
      }
    }

    // POST: Schedules/Create
    [HttpPost]
    public IActionResult Create(ScheduleViewModel viewModel)
    {
      var schedule = viewModel.Transform<ScheduleViewModel, Schedule>((vm, s) =>
      {
        s.Client = _facade.GetUserService().FindClient(CurrentUser.Id);
        s.Treatment = _facade.GetTreatmentService().Find(vm.TreatmentId);
      });

      var result = _facade.GetScheduleService().Add(schedule);
      return RespondTo(result, RedirectToAction("Index"), Create());
    }

    // GET: Schedules/Edit/5
    public IActionResult Edit(int id)
    {
      BeforeCreateOrEdit();

      var schedule = _facade.GetScheduleService().Find(id).Transform<Schedule, ScheduleViewModel>();
      if (schedule.Client.Id == CurrentUser.Id)
      {
        return View(schedule);
      }
      else
      {
        return RedirectToAction("Index");
      }
    }

    // POST: Schedules/Edit/5
    [HttpPost]
    public IActionResult Edit(int id, ScheduleViewModel viewModel)
    {

      var schedule = viewModel.Transform<ScheduleViewModel, Schedule>((vm, s) =>
      {
        s.Client = _facade.GetUserService().FindClient(vm.ClientId);
        s.Treatment = _facade.GetTreatmentService().Find(vm.TreatmentId);
      });
      var result = _facade.GetScheduleService().Update(schedule);

      return RespondTo(result, RedirectToAction("Index"), Edit(id));
    }

    // GET: Schedules/Delete/5
    public IActionResult Delete(int id)
    {
      var schedule = _facade.GetScheduleService().Find(id).Transform<Schedule, ScheduleViewModel>();
      return View(schedule);

    }

    // POST: /Schdules/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public IActionResult DeleteConfirmed(int id)
    {
      var result = _facade.GetScheduleService().Remove(id);

      return RespondTo(result, RedirectToAction("Index"), Delete(id));
    }

    //private methods

    private void BeforeCreateOrEdit()
    {
      LoadTreatments();
      LoadStartTimes();
      LoadMySchedules();
      LoadSessionDurations();
    }
    private void LoadSessionDurations()
    {
      var items = new List<SelectListItem>()
      {
        new SelectListItem { Text = "Choose one...", Value="" },
        new SelectListItem { Text = "30 minutes", Value="00:30:00" },
        new SelectListItem { Text = "1 hour", Value="1:00:00" }
      };
      ViewBag.SessionDurations = items;
    }

    private void LoadTreatments()
    {
      var treatments = _facade.GetTreatmentService().GetAll().Select(c =>
        new SelectListItem()
        {
          Text = c.Name,
          Value = c.Id.ToString()
        });
      treatments = treatments.Prepend(new SelectListItem()
      {
        Text = "Choose one...",
        Value = ""
      });
      ViewBag.Treatments = treatments;
    }

    private void LoadMySchedules()
    {
      List<Schedule> items = _facade.GetScheduleService().GetMySchedules(CurrentUser);
      ViewBag.MySchedules = items.Transform<Schedule, ScheduleViewModel>();
    }

    private void LoadStartTimes()
    {

      var items = new List<SelectListItem>()
      {
        new SelectListItem { Text = "Choose one...", Value="" },
        new SelectListItem { Text = "6:00", Value="06:00:00" },
        new SelectListItem { Text = "6:30", Value="06:30:00" },
        new SelectListItem { Text = "7:00", Value="07:00:00" },
        new SelectListItem { Text = "7:30", Value="07:30:00" },
        new SelectListItem { Text = "8:00", Value="08:00:00" },
        new SelectListItem { Text = "8:30", Value="08:30:00" },
        new SelectListItem { Text = "9:00", Value="09:00:00" },
        new SelectListItem { Text = "9:30", Value="09:30:00" },
        new SelectListItem { Text = "10:00", Value="10:00:00" },
        new SelectListItem { Text = "10:30", Value="10:30:00" },
        new SelectListItem { Text = "11:00", Value="11:00:00" },
        new SelectListItem { Text = "11:30", Value="11:30:00" },
        new SelectListItem { Text = "12:00", Value="12:00:00" },
        new SelectListItem { Text = "12:30", Value="12:30:00" },
        new SelectListItem { Text = "13:00", Value="13:00:00" },
        new SelectListItem { Text = "13:30", Value="13:30:00" },
        new SelectListItem { Text = "14:00", Value="14:00:00" },
        new SelectListItem { Text = "14:30", Value="14:30:00" },
        new SelectListItem { Text = "15:00", Value="15:00:00" },
        new SelectListItem { Text = "15:30", Value="15:30:00" },
        new SelectListItem { Text = "16:00", Value="16:00:00" },
        new SelectListItem { Text = "16:30", Value="16:30:00" },
        new SelectListItem { Text = "17:00", Value="17:00:00" },
        new SelectListItem { Text = "17:30", Value="17:30:00" },
        new SelectListItem { Text = "18:00", Value="18:00:00" },
        new SelectListItem { Text = "18:30", Value="18:30:00" },
        new SelectListItem { Text = "19:00", Value="19:00:00" },
        new SelectListItem { Text = "19:30", Value="19:30:00" },
        new SelectListItem { Text = "20:00", Value="20:00:00" },
        new SelectListItem { Text = "20:30", Value="20:30:00" },
        new SelectListItem { Text = "21:00", Value="21:00:00" },
        new SelectListItem { Text = "21:30", Value="21:30:00" },
        new SelectListItem { Text = "22:00", Value="22:00:00" },
        new SelectListItem { Text = "22:30", Value="22:30:00" },



      };
      ViewBag.StartTimes = items;
    }

  }
}

ClinicalAgenda.Web.MVC/Views/Shared/_Layout.cshtml

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>

    <environment include="Development">
      <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
      <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
      <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/4.1.3/css/bootstrap.min.css"
            asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
            asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
      <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
  </head>
  <body>
    <partial name="_CookieConsentPartial" />
    <nav class="navbar menu navbar-expand-lg navbar-dark bg-dark ">
      <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">
        <img src=~/images/logo_40h.png />
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index" class="nav-link">Home</a></li>
          </li>
          
          @if (@ViewBag.CurrentUser != null){
            <li><a asp-area="" asp-controller="Schedules" asp-action="Index" class="nav-link">Schedules</a></li>
            @if (!ViewBag.IsClient){
              <li><a asp-area="" asp-controller="Clients" asp-action="Index" class="nav-link">Clients</a></li>
              <li><a asp-area="" asp-controller="Treatments" asp-action="Index" class="nav-link">Treatments</a></li>
            }
          }
      
          @if (@ViewBag.CurrentUser != null){
            <ul class="nav navbar-nav  ">
              <li class="nav-item dropdown">
                <a href="#" class=" nav-link dropdown-toggle" data-toggle="dropdown">
                  @ViewBag.CurrentUser.Name @ViewBag.CurrentUser.Surname <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                  @if (ViewBag.IsClient){
                    <li><a class="dropdown-item" asp-area="" asp-controller="Clients" asp-action="Details" asp-route-id="@ViewBag.CurrentUser.Id">Edit Your Profile</a></li>
                    <div class="dropdown-divider"></div>
                  }
                  
                  <li><a class="dropdown-item" asp-area="" asp-controller="Sessions" asp-action="Destroy">Logout</a></li>
                </ul>
              </li>
            </ul>
          }
        </ul>    
      </div>
    </nav>

    

    <div class="container body-content">
      @RenderBody()
      <hr />
      <footer>
        <p>&copy; 2018 - ClinicalAgenda</p>
      </footer>
    </div>

    <environment include="Development">
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
      <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
      <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    <partial name="_ValidationScriptsPartial" />
    

    @RenderSection("Scripts", required: false)
  </body>
</html>

ClinicalAgenda.Web.MVC/Views/Shared/_ScheduleList.cshtml
@model IEnumerable<ClinicalAgenda.Web.MVC.Models.ScheduleViewModel>

@if (@Model == null) {
  <div class="d-flex justify-content-between flex-wrap">
    Nothing here yet.
  </div>
} else {
  <div class="d-flex justify-content-between flex-wrap">
    @foreach (var item in @Model) { 
      var cardType = item.Treatment.Type == TreatmentType.Massage ? "bg-warning" : "bg-info";
      
      <div class="card mb-4 @cardType w-100" >
        <div class="card-header">
          <span class="align-middle card-header-title"><b>@Html.DisplayFor(modelItem => item.Treatment.Name)</b></span>
          <div class="btn-group float-right" role="group">
            <a class="btn btn-dark btn-sm" asp-controller="Schedules" asp-action="Details" asp-route-id="@item.Id">View Details</a>
            @if (item.Client.Id == ViewBag.CurrentUser.Id) {
              <a class="btn btn-secondary btn-sm" asp-controller="Schedules" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
              <a class="btn btn-danger btn-sm" asp-controller="Schedules" asp-action="Delete" asp-route-id="@item.Id">Cancel</a>
            }
          </div> 
        </div>
        <div class="card-body">
          <div class="row">
            <div class="col text-right" >
              <b>@Html.DisplayNameFor(modelItem => item.StartTime):</b>
            </div>
            <div class="col" >
              @Html.DisplayFor(modelItem => item.StartDate) @Html.DisplayFor(modelItem => item.StartTime)
            </div>
          
            <div class="col text-right" >
              <b>@Html.DisplayNameFor(modelItem => item.SessionDuration):</b>
            </div>
            <div class="col" >
              @Html.DisplayFor(modelItem => item.SessionDuration)
            </div>
          
            @if (!ViewBag.IsClient){
              <div class="col text-right" >
                <b>@Html.DisplayNameFor(modelItem => item.Client):</b>
              </div>
              <div class="col" >
                @Html.DisplayFor(modelItem => item.Client.Name) @Html.DisplayFor(modelItem => item.Client.Surname)
              </div>
            }
          </div>
        </div>
      </div>
    }
  </div> 
}